### ISSUE TITLE
Is there any way to insert data to collection through mongotron gui? 

### ISSUE THREAD

**Issue by CurlyHeir** [officert/mongotron#135]
Hi, 
when i try to put some data by 
```
db.users.insert({
name:"username",
type:"FOOL"
});
```

i'm getting error: 
```
Error : db.startup_log.insert is not a function TypeError: db.users.insert is not a function at evalmachine.:1:16 at ContextifyScript.Script.runInNewContext (vm.js:18:15) at /Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:170:23 at Promise._execute (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:159:9) at Promise._resolveFromExecutor (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:460:18) at new Promise (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:76:14) at _eval (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:140:10) at /Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:39:9 at Promise._execute (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:159:9) at Promise._resolveFromExecutor (/Applications/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:460:18)
```

is there even possibility to add data in that way?

**Comment by officert** [comment]
Yea try insertOne or insertMany, mongotron's API is just a wrapper around the Node ha Mongodb driver, so you can always look at their docs for the methods you can use.

**Comment by CurlyHeir** [comment]
i'm begginer with MongoDB, thanks for advice, it worked 👍 
 
Have you thought about adding "insert with GUI" feature? 
for instance add item button would display view with template based on existing items - it would be brilliant ;)

**Comment by officert** [comment]
that's a great idea! If it's something you'd like to see in Mongotron do
you mind creating a new issue for it and putting in as much info/detail as
you can think of how the feature might work? Thanks!
