### ISSUE TITLE
count() is not a function

### ISSUE THREAD

**Issue by web707172** [officert/mongotron#155]
`db.region.find({dmId:{$gt:3}}).count()`
error message
`
Error : db.region.find(...).count is not a function TypeError: db.region.find(...).count is not a function at evalmachine.:1:32 at ContextifyScript.Script.runInNewContext (vm.js:18:15) at 
`

**Comment by apisurfer** [comment]
I'd add db.collection.remove to this:
`remove is not a function at evalmachine.:1:12 at ContextifyScript.Script.runInNewContext (vm.js:18:15) `
