### ISSUE TITLE
Getting 'Cannot find module 'internal/util/types' error when running 'npm install'

### ISSUE THREAD

**Issue by grzeczko** [officert/mongotron#170]
I'm getting a 'Cannot find module 'internal/util/types' error when running 'npm install'.

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/.../Desktop/mongotron-master/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

I'm using:
Node v8.9.4
NPM v5.6.0

**Comment by mikk351** [comment]
Same error with same node and npm version. On fedora 27.

**Comment by OwlLaboratory** [comment]
Same error !

**Comment by T-vK** [comment]
Same here on Fedora 27 as well.

**Comment by creative-cranels** [comment]
Same on Ubuntu 16.04 LTS :(

**Comment by danangpn** [comment]
same error on Fedora 28

**Comment by nisuxyz** [comment]
I am getting the same error with yarn and npm.

Fedora 28
yarn v1.7.0
npm v5.6.0
node v8.11.3

**Comment by echo66** [comment]
I'm getting the same error

**Comment by neonihil** [comment]
I ran into the same issue on fedora 28. It seems to be problem with bower as it fails during the bower install phase of npm install.

```
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> electron-prebuilt@0.36.7 postinstall /home/vagrant/mongotron/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.7-linux-x64.zip
[============================================>] 100.0% of 38.36 MB (1.17 MB/s)

> Mongotron@1.0.0-alpha.5 postinstall /home/vagrant/mongotron
> bower install && gulp dev-sym-links

module.js:550
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/home/vagrant/mongotron/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Mongotron@1.0.0-alpha.5 postinstall: `bower install && gulp dev-sym-links`
npm ERR! Exit status 1
npm ERR! 
```

The bower team has a closed issue regarding this:

https://github.com/bower/bower/issues/2497

The most upvoted comment is the one saying to use node < 7.0 (so like 6.9).

I'm not sure where to go from here.

**Comment by abileshkumart** [comment]
how to fix this error
![error](https://user-images.githubusercontent.com/42779987/50881203-eb352a00-1406-11e9-9521-44b87af3c109.PNG)

**Comment by KaKi87** [comment]
This issue is more than a year old and it's still happening to me today. Please @officert say something
