### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by paragasu** [officert/mongotron#179]
Cloning the repo and running npm install, i got the following error. I am using mac catalina.

```$ npm install

> Mongotron@1.0.0-alpha.5 postinstall /Users/phisoftware/bin/mongotron
> bower install && gulp dev-sym-links

evalmachine.<anonymous>:33
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:33:5
    at Object.<anonymous> (/Users/phisoftware/bin/mongotron/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/phisoftware/bin/mongotron/node_modules/bower/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)```

**Comment by re8260** [comment]
+1 Ubuntu 19.4

```
$ ./node_modules/.bin/bower install && gulp dev-sym-links
evalmachine.<anonymous>:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:35:5


```

**Comment by emersonbottero** [comment]
any workaround?

**Comment by emersonbottero** [comment]
You need to modify your package.json this way:

{
  // Your current package.json
  "scripts": {
    // Your current package.json scripts
    "preinstall": "npx npm-force-resolutions"
  },
  "resolutions": {
    "graceful-fs": "4.2.3"
  }
}

from [stackoverflow](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node)

**Comment by bigshans** [comment]
Still not work. Is there any other workaround?
