### ISSUE TITLE
Add support for developing on Windows

### ISSUE THREAD

**Issue by officert** [officert/mongotron#19]

**Comment by jojobyte** [comment]
On Node v4.2.2 when running  `npm install` postinstall fails with:

```
> Mongotron@1.0.0-alpha.1 postinstall C:\code\mongotron
> make postinstall

cd ./node_modules;  ln -snfv ../src src;  ln -snfv ../src/lib lib;  ln -snfv ../tests tests;
--- errorlevel 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Mongotron@1.0.0-alpha.1 postinstall: `make postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mongotron@1.0.0-alpha.1 postinstall script 'make postinstall'.
npm ERR! This is most likely a problem with the Mongotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls Mongotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\mongotron\npm-debug.log
```

Ignoring that error and running `bower install` works fine, then we skip `make postinstall` as we already know it fails, and try `gulp serve` but it fails with:

```
[01:31:35] Using gulpfile C:\code\mongotron\gulpfile.js
[01:31:35] Starting 'clean'...
[01:31:35] Finished 'clean' after 1.12 ms
[01:31:35] Starting 'css'...
[01:31:35] Starting 'dev-sym-links'...
[01:31:35] Finished 'dev-sym-links' after 7.25 ms
stdout: cd ./node_modules;  ln -snfv ../src src;  ln -snfv ../src/lib lib;  ln -snfv ../tests tests;
--- errorlevel 1

stderr:
exec error: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "make createDevelopmentSymLinks"

[01:31:36] Finished 'css' after 872 ms
[01:31:36] Starting 'build'...
[01:31:36] Finished 'build' after 7.01 μs
[01:31:36] Starting 'serve'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/electron ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Now try to be tricky by running `electron .` but it fails with:

![Windows Electron Error](http://cl.ly/image/0d3N0k0I0A0d/Image%202015-12-03%20at%201.35.11%20AM.png)
