### ISSUE TITLE
Failed at the Mongotron@1.0.0-alpha.1 postinstall script 'gulp dev-sym-links'.

### ISSUE THREAD

**Issue by gopalindians** [officert/mongotron#59]
>C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron>npm install

npm WARN install Couldn't install optional dependency: Unsupported

> Mongotron@1.0.0-alpha.1 postinstall C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron
> gulp dev-sym-links

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 
>  C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron\gulpfile.js:16:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm WARN EPEERINVALID mongodb-core@1.2.28 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Mongotron@1.0.0-alpha.1 postinstall: `gulp dev-sym-links`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mongotron@1.0.0-alpha.1 postinstall script 'gulp dev-sym-links'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Mongotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dev-sym-links
npm ERR! You can get their info via:
npm ERR!     npm owner ls Mongotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\abc\WebstormProjects\Html5AndCss3\mongotron\mongotron\npm-debug.log

**Comment by Kreshnik** [comment]
Same issue, see my system info below;
>Linux Mint 17.3
And find attached the `npm-debug.log` file.
[npm-debug.txt](https://github.com/officert/mongotron/files/72543/npm-debug.txt)
