### ISSUE TITLE
Meteor Mongo Connection

### ISSUE THREAD

**Issue by fallenpeace** [officert/mongotron#84]
I love the mongotron UI, but it fails connecting to Meteor's Mongo Database

host: 127.0.0.1
port: 3001

username and password are empty.

**Comment by officert** [comment]
Are you seeing an errors? Do you have ```mongod```? Need more info, maybe a screenshot.

**Comment by fallenpeace** [comment]
@officert Mongod is running. But yes sorry forgot to include the error.

Message: Field Missing/Wrong Type in received authenticate command

**Comment by officert** [comment]
Sounds like it could be an issue related to Mongo 3 and the new authentication mechanism.

https://github.com/andzdroid/mongo-express/issues/55

Can you tell me what version of MongoDB you're using? and which version of Mongotron are you using?

thanks @fallenpeace !

**Comment by fallenpeace** [comment]
@officert 

Meteor uses 2.6.7, here is the logged events that happen when mongotron tries to connect, if it helps.


```
2016-01-20T14:48:15.388-0800 [initandlisten] connection accepted from 127.0.0.1:52687 #34 (25 connections now open)
2016-01-20T14:48:15.389-0800 [initandlisten] connection accepted from 127.0.0.1:52688 #35 (26 connections now open)
2016-01-20T14:48:15.389-0800 [initandlisten] connection accepted from 127.0.0.1:52689 #36 (27 connections now open)
2016-01-20T14:48:15.389-0800 [initandlisten] connection accepted from 127.0.0.1:52690 #37 (28 connections now open)
2016-01-20T14:48:15.390-0800 [initandlisten] connection accepted from 127.0.0.1:52691 #38 (29 connections now open)
2016-01-20T14:48:15.391-0800 [conn34]  authenticate db: meteor { authenticate: 1, user: null, nonce: "xxx", key: "xxx" }
2016-01-20T14:48:15.392-0800 [conn35]  authenticate db: meteor { authenticate: 1, user: null, nonce: "xxx", key: "xxx" }
2016-01-20T14:48:15.392-0800 [conn36]  authenticate db: meteor { authenticate: 1, user: null, nonce: "xxx", key: "xxx" }
2016-01-20T14:48:15.392-0800 [conn37]  authenticate db: meteor { authenticate: 1, user: null, nonce: "xxx", key: "xxx" }
2016-01-20T14:48:15.392-0800 [conn38]  authenticate db: meteor { authenticate: 1, user: null, nonce: "xxx", key: "xxx" }
2016-01-20T14:48:15.402-0800 [conn34] Failed to authenticate @meteor with mechanism MONGODB-CR: ProtocolError field missing/wrong type in received authenticate command
2016-01-20T14:48:15.403-0800 [conn36] Failed to authenticate @meteor with mechanism MONGODB-CR: ProtocolError field missing/wrong type in received authenticate command
2016-01-20T14:48:15.403-0800 [conn35] Failed to authenticate @meteor with mechanism MONGODB-CR: ProtocolError field missing/wrong type in received authenticate command
2016-01-20T14:48:15.403-0800 [conn37] Failed to authenticate @meteor with mechanism MONGODB-CR: ProtocolError field missing/wrong type in received authenticate command
2016-01-20T14:48:15.403-0800 [conn38] Failed to authenticate @meteor with mechanism MONGODB-CR: ProtocolError field missing/wrong type in received authenticate command
```

**Comment by officert** [comment]
@fallenpeace are you using the v1.0.0-alpha.2 of Mongotron? 

https://github.com/officert/mongotron/releases

if so, I think there is a fix in the latest code but I haven't created a new release for it yet.

**Comment by fallenpeace** [comment]
@officert I wasn't, but same issue.

However :), I was finally able to connect with both the official release and alpha.2, I omitted the database name when setting up the connecting inside of mongotron and success!

Connection Name: Meteor
Database Name: 
Host: 127.0.0.1
Port: 3001
Username:
Password:

Awesome, well there's that.
Love the work you've done with mongotron. I was previously looping through other mongo GUI's and their interfaces are just meh, compared with this one.

**Comment by officert** [comment]
@fallenpeace do you mind updating to the latest code and seeing if you get the same issue. I just pushed a commit 

https://github.com/officert/mongotron/commit/dd02f1e38278579f1051a13ae1a082cc632873fb

The problem was when we check if the connection is to localhost we were only checking for 'localhost', not '127.0.0.1'.

**Comment by officert** [comment]
@fallenpeace Thanks! glad you like it :+1:  

If you have any feedback or features you'd like to see implemented would love to hear

https://github.com/officert/mongotron/issues/46

**Comment by fallenpeace** [comment]
I couldn't update to the latest commit. I get errors.

```
[14:10:50] gulp-symlink:/Users/Aphects/Development/oss/mongotron-master/src symlinked to ./node_modules/src
[14:10:50] gulp-symlink:/Users/Aphects/Development/oss/mongotron-master/src/lib symlinked to ./node_modules/lib
Potentially unhandled rejection [2] '../vendor/bootstrap/less/bootstrap.less' wasn't found. Tried - /Users/Aphects/Development/oss/mongotron-master/src/ui/vendor/bootstrap/less/bootstrap.less,../vendor/bootstrap/less/bootstrap.less in file /Users/Aphects/Development/oss/mongotron-master/src/ui/less/main.less line no. 2
[14:10:50] gulp-symlink:/Users/Aphects/Development/oss/mongotron-master/tests symlinked to ./node_modules/tests
[14:10:50] gulp-symlink:/Users/Aphects/Development/oss/mongotron-master/package.json symlinked to ./node_modules/package.json
[14:10:50] Finished 'dev-sym-links' after 78 ms
```


Basically bootstrap and font-awesome are messing from the "vendor" folder, even after the "npm install" So i pulled them in from NPM.



Then when i do gulp release I get the following error.

```
[14:17:57] Starting 'release'...
Packaging app for platform linux ia32 using electron v0.36.0
[14:18:07] 'release' errored after 9.64 s
[14:18:07] Error: Command failed: /bin/sh -c npm prune --production
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "prune" "--production"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! path /private/tmp/electron-packager/linux-ia32/Mongotron-linux-ia32/resources/app/node_modules/.bin/babylon
npm ERR! code EEXIST

npm ERR! Refusing to delete /private/tmp/electron-packager/linux-ia32/Mongotron-linux-ia32/resources/app/node_modules/.bin/babylon: is outside /private/tmp/electron-packager/linux-ia32/Mongotron-linux-ia32/resources/app/node_modules/babylon and not a link
npm ERR! File exists: /private/tmp/electron-packager/linux-ia32/Mongotron-linux-ia32/resources/app/node_modules/.bin/babylon
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/electron-packager/linux-ia32/Mongotron-linux-ia32/resources/app/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by fallenpeace** [comment]
Closing this, as I have fixed my issues.

Fixed this by fixing NPM permission and moving away from using "sudo" to install npm packages and moved the npm config prefix directory to a folder in my home directory. No more failures :)

**Comment by officert** [comment]
thanks @fallenpeace glad you were able to resolve things. I need to do some more testing with NPM 3.
